apiVersion: skaffold/v4beta11
kind: Config
profiles:
  - name: database
    activation:
      - env: DATABASE=1
        kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: ems-db
            remoteChart: oci://registry-1.docker.io/bitnamicharts/mysql
            wait: true
            setValueTemplates:
              auth.rootPassword: root
    portForward:
      - resourceName: ems-db-mysql
        resourceType: service
        address: 127.0.0.1
        port: 3306
        localPort: 3306

  - name: influx
    activation:
      - env: INFLUX=1
        kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: ems-influx
            remoteChart: influxdb2
            repo: https://helm.influxdata.com
            wait: true
            setValueTemplates:
              adminUser:
                organization: eeprom-monitoring-server
                bucket: ems
                user: admin
                retention_policy: 24h
                password: long_password
                token: v3rY-d1ff1cUlT-t0k3n
    portForward:
      - resourceName: ems-influx-influxdb2
        resourceType: service
        address: 127.0.0.1
        port: 80
        localPort: 8086