---
# Web credentials 
Users:
  ems_login: ems_password
# MySQL config
Database:
  User: http
  Passwd: http-password
  Net:    tcp
  Addr:   127.0.0.1:3306
  DBName: http-database
# Port for devices' config page
Port: 80
# Time steps for loop
Intervals: # in seconds
  StartupDelay: 15
  SqlQueryInt: 50 # syncing with database
  SshQueryInt: 5 # polling devices over SSH
# Influx config
Influx:
  Bucket: ems-bucket
  Org: eeprom-monitoring-server
  Token: v3rY-d1ff1cUlT-t0k3n
  Url: http://localhost:8086
  Retention: 24h
...
