---
# Frontend and MySQL config
Users:
  login: password
  admin: rEaL_4dm1n
Database:
  User: db_user
  Passwd: StRoNgPaSsWoRd
  Net:    tcp
  Addr:   127.0.0.1:3306
  DBName: sample_database
Port: 80

# Time steps for backend
Intervals: # in seconds
  StartupDelay: 15
  SqlQueryInt: 50 # sync with database
  SshQueryInt: 5 # polling devices over SSH
...
