openapi: 3.1.1
info:
  title: EMS frontend API
  description: An API for accessing configuration page of EEPROM Monitoring Server
  license:
    name: GNU General Public License version 3 or later
    identifier: GPL-3.0-or-later
  version: 0.1.0

paths:
  /signin:
    get:
      summary: Load signin page
      responses:
        200:
          description: Returns the signin landing page
          $ref: '#/components/responses/Page'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security: []
    post:
      summary: Handle login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                login:
                  type: string
                  format: email
                  pattern: '^[a-zA-Z0-9]([-_.a-zA-Z0-9]){1,31}$'
                  minLength: 2
                  maxLength: 32
                password:
                  type: string
                  format: password
              required:
              - login
              - password
      responses:
        200:
          description: Wrong credentials
          $ref: '#/components/responses/Page'
        303:
          description: Login success
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security: []

  /:
    get:
      summary: Main configuration page
      responses:
        200:
          description: Returns the main configuration page
          $ref: '#/components/responses/Page'
        303:
          description: Unauthorized
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security:
      - cookieAuth: []

  /new:
    get:
      summary: Load New device page
      responses:
        200:
          description: Returns the New device page
          $ref: '#/components/responses/Page'
        303:
          description: Unauthorized
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
    post:
      summary: Create new device
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                hostname:
                  type: string
                ip:
                  type: string
                ip-type:
                  $ref: '#/components/schemas/ipType'
                login:
                  type: string
                  pattern: '^[a-zA-Z][-._a-zA-Z0-9]*[a-zA-Z0-9]$'
                password:
                  type: string
                  format: password
                key:
                  type: string
                  format: binary
              required:
              - hostname
              - ip
              - ip-type
              - login
      responses:
        200:
          description: Returns New device page (might be with error)
          $ref: '#/components/responses/Page'
        303:
          description: Device created or Unauthorized (redirects to /)
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security:
      - cookieAuth: []

  /edit:
    get:
      summary: Load Edit device page
      parameters:
      - in: query
        name: edit-id
        required: true
        schema:
          type: integer
          format: uint
      responses:
        200:
          description: Returns the Edit device page
          $ref: '#/components/responses/Page'
        303:
          description: Unauthorized
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security:
      - cookieAuth: []
    post:
      summary: Update device
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                edit-id:
                  type: integer
                  format: uint
                hostname:
                  type: string
                ip:
                  type: string
                ip-type:
                  $ref: '#/components/schemas/ipType'
                login:
                  type: string
                  pattern: '^[a-zA-Z][-._a-zA-Z0-9]*[a-zA-Z0-9]$'
                password:
                  type: string
                  format: password
                password-clear:
                  type: string
                  format: "^on$"
                key:
                  type: string
                  format: binary
                key-clear:
                  type: string
                  format: "^on$"
              required:
              - edit-id
              - hostname
              - ip
              - ip-type
              - login
      responses:
        200:
          description: Returns initial Edit device page (might be with error)
          $ref: '#/components/responses/Page'
        303:
          description: Device updated or Unauthorized (redirect to /)
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security:
      - cookieAuth: []

  /delete:
    post:
      summary: Load Edit device page
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                delete-id:
                  type: integer
                  format: uint
              required:
              - delete-id
      responses:
        303:
          description: Device deleted or Unauthorized (redirect to /)
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'
      security:
      - cookieAuth: []

  /logout:
    get:
      parameters:
      - in: cookie
        name: session_token
        schema:
          type: string
      summary: Log out
      responses:
        303:
          description: Logs out and redirects to /signin
          $ref: '#/components/responses/PageRedirect'
        500:
          description: Internal server error
          $ref: '#/components/responses/PageError'

  /static/favicon.ico:
    get:
      summary: Serve the favicon
      responses:
        200:
          description: The favicon
          content:
            image/x-icon:
              schema:
                type: string
                format: binary
      security: []

  /static/style.css:
    get:
      summary: Serve the CSS stylesheet
      responses:
        200:
          description: The CSS stylesheet
          content:
            text/css:
              schema:
                type: string
      security: []

components:
  schemas:
    ipType:
      type: integer
      enum:
      - 4
      - 6

  responses:
    Page:
      description: Load requested page
      content:
        text/html:
          schema:
            type: string

    PageRedirect:
      description: Redirect to page
      headers:
        Location:
          description: Direction of redirect
          schema:
            type: string
            example: /signin
            enum:
            - /
            - /signin
    
    PageError:
      description: Load requested page with error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Error message'
              errorDetails:
                type: string
                example: 'Error detailed message'
            required:
            - error

  securitySchemes:
    cookieAuth:
      type: apiKey
      name: session_token
      in: cookie
